# Generated by Django 4.2.7 on 2023-12-05 06:04

import autoslug.fields
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Careers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=1000)),
                ('link', models.URLField(max_length=1000)),
                ('career_slug', autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='title', unique=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=1000)),
                ('description', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='programimg')),
                ('created_date', models.DateField(auto_now=True)),
                ('program_slug', autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='title', unique=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=1000)),
                ('description', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='serviceimg')),
                ('created_date', models.DateField(auto_now=True)),
                ('service_slug', autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='title', unique=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
