# Generated by Django 4.2.7 on 2023-12-05 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_about_event_rename_title_careers_title_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
