# Generated by Django 4.2.7 on 2023-12-05 09:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.TimeField()),
                ('endtime', models.TimeField()),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('eventname', models.CharField(max_length=500)),
                ('description', ckeditor.fields.RichTextField()),
                ('location', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='eventimg/')),
            ],
        ),
    ]
