# Generated by Django 4.2.7 on 2023-12-05 09:59

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='eventname', unique=True),
        ),
    ]
