# Generated by Django 4.2.7 on 2023-12-06 05:01

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_team_team_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='organizationchart',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='careers',
            name='career_slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from='title', unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from='eventname', unique=True),
        ),
        migrations.AlterField(
            model_name='organizationchart',
            name='org_slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='program_slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from='title', unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from='title', unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True),
        ),
    ]
