# Generated by Django 4.2.7 on 2023-12-06 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_event_options_alter_organizationchart_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationchart',
            name='order_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
