# Generated by Django 4.2.7 on 2023-12-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_representinstitute_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_img', models.FileField(upload_to='sliderimages/')),
                ('title', models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('contact', 'Contact'), ('service', 'Service'), ('program', 'Program'), ('career', 'Career')], max_length=200)),
            ],
        ),
    ]
