# Generated by Django 4.2.7 on 2023-12-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_sliderimg_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_info',
            name='logo',
            field=models.ImageField(default=1, upload_to='logo'),
            preserve_default=False,
        ),
    ]
