# Generated by Django 4.2.7 on 2023-12-07 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_delete_about_company_info_intstudent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breadcrumb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breadcrumb_img', models.FileField(upload_to='sliderimages/')),
                ('title', models.CharField(choices=[('about', 'About'), ('contact', 'Contact'), ('service', 'Service'), ('program', 'Program'), ('career', 'Career')], max_length=200)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.RemoveField(
            model_name='sliderimg',
            name='title',
        ),
        migrations.AddField(
            model_name='sliderimg',
            name='order_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
