# Generated by Django 4.2.7 on 2023-12-07 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_breadcrumb_remove_sliderimg_title_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SliderImg',
        ),
    ]
