# Generated by Django 4.2.7 on 2023-12-07 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_delete_sliderimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_img', models.FileField(upload_to='sliderimages/')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
