# Generated by Django 4.2.7 on 2023-12-07 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_sliderimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderimg',
            name='title',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
