# Generated by Django 4.2.7 on 2023-12-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_sliderimg_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breadcrumb',
            name='breadcrumb_img',
            field=models.FileField(upload_to='images/'),
        ),
    ]
