# Generated by Django 4.2.7 on 2023-12-07 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_breadcrumb_breadcrumb_img'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Program',
            new_name='Programs',
        ),
    ]
