# Generated by Django 4.2.7 on 2023-12-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_rename_program_programs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breadcrumb',
            name='title',
            field=models.CharField(choices=[('about', 'About'), ('contact', 'Contact'), ('service', 'Service'), ('program', 'Program'), ('career', 'Career'), ('event', 'Event')], max_length=200),
        ),
    ]
